# GODMAX xDESI Stage-31 Local HMC Debug Run

This notebook runs the fixed-cosmology Stage-31 sampler interactively, without Slurm. It is intentionally verbose: each expensive step prints a timestamp, reports the JAX backend, checks whether the fiducial model value is finite, checks whether NumPyro can initialize gradients, and only then runs NUTS.

If initialization fails, inspect the diagnostic cells before running the sampler cell. The current known failure mode is finite likelihood value but invalid gradients through the GODMAX/HOD theory path.

In [22]:
# This cell must run before importing JAX in a fresh kernel.
# Restart the kernel first if JAX was already imported and you want these settings to apply.
import os

USE_GPU = True
GPU_MEM_FRACTION = "0.95"
RUN_GPU_SANITY_CHECK = True
GPU_SANITY_MATRIX_SIZE = 4096

if USE_GPU:
    os.environ["JAX_PLATFORMS"] = "cuda"
else:
    os.environ["JAX_PLATFORMS"] = "cpu"

print("Using GPU:", USE_GPU)

os.environ["JAX_ENABLE_X64"] = "True"
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "true"
os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"] = GPU_MEM_FRACTION

print("JAX_PLATFORMS=", os.environ.get("JAX_PLATFORMS"))
print("XLA_PYTHON_CLIENT_PREALLOCATE=", os.environ.get("XLA_PYTHON_CLIENT_PREALLOCATE"))
print("XLA_PYTHON_CLIENT_MEM_FRACTION=", os.environ.get("XLA_PYTHON_CLIENT_MEM_FRACTION"))

Using GPU: True
JAX_PLATFORMS= cuda
XLA_PYTHON_CLIENT_PREALLOCATE= true
XLA_PYTHON_CLIENT_MEM_FRACTION= 0.95

In [23]:
from __future__ import annotations

import json
import os
import sys
import time
import traceback
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd


def find_repo_root(start: Path | None = None) -> Path:
    start = (start or Path.cwd()).resolve()
    for candidate in (start, *start.parents):
        if (candidate / "param_files").is_dir() and (candidate / "src").is_dir():
            return candidate
    raise RuntimeError(f"Could not find GODMAX repo root from {start}")


REPO_ROOT = find_repo_root()
os.chdir(REPO_ROOT)
SURVEY_DIR = REPO_ROOT / "notebooks" / "xDESI" / "survey_measure"
if str(SURVEY_DIR) not in sys.path:
    sys.path.insert(0, str(SURVEY_DIR))

print("repo root:", REPO_ROOT)
print("survey dir:", SURVEY_DIR)

# try:
get_ipython().run_line_magic("load_ext", "autoreload")
get_ipython().run_line_magic("autoreload", "2")
# except Exception:
#     pass

repo root: /mnt/ceph/users/spandey/ltu-godmax/GODMAX
survey dir: /mnt/ceph/users/spandey/ltu-godmax/GODMAX/notebooks/xDESI/survey_measure
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [24]:

import jax
import jax.numpy as jnp
import numpyro

import godmax_multiprobe_hmc_stage31 as hmc31

PLATFORM = "gpu" if USE_GPU else "cpu"
runtime = hmc31.configure_numpyro_platform(PLATFORM)
print(json.dumps(runtime, indent=2))
print("jax_enable_x64:", jax.config.jax_enable_x64)

if RUN_GPU_SANITY_CHECK:
    gpu_check = hmc31.gpu_sanity_check(GPU_SANITY_MATRIX_SIZE, require_gpu=USE_GPU)
    print("gpu sanity check")
    print(json.dumps(hmc31.gmt.to_jsonable(gpu_check), indent=2))

{
  "requested_platform": "gpu",
  "jax_default_backend": "gpu",
  "jax_device_count": 1,
  "jax_device_platforms": [
    "gpu"
  ],
  "jax_devices": [
    "cuda:0"
  ]
}
jax_enable_x64: True
gpu sanity check
{
  "jax_default_backend": "gpu",
  "jax_device_platforms": [
    "gpu"
  ],
  "jax_devices": [
    "cuda:0"
  ],
  "matrix_size": 4096,
  "result": 68719476736.0,
  "seconds": 0.00593113899230957
}

In [25]:

def now() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def mark(message: str) -> None:
    print(f"[{now()}] {message}", flush=True)


def run_step(label: str, func):
    mark(f"START {label}")
    t0 = time.time()
    try:
        out = func()
    except Exception as exc:
        mark(f"FAILED {label} after {time.time() - t0:.1f} s: {type(exc).__name__}: {exc}")
        traceback.print_exc(limit=12)
        raise
    mark(f"DONE {label} in {time.time() - t0:.1f} s")
    return out

## Controls

Use `RUN_MODE = "smoke"` for an interactive test. Switch to `"full"` only after the initialization diagnostics are clean. You can override any sampler setting below without editing the YAML.

In [26]:
CONFIG = REPO_ROOT / "param_files" / "xDESI" / "params_multiprobe_fast1024_hmc_stage31.yaml"
RUN_MODE = "smoke"  # "smoke" or "full"
SMOKE = RUN_MODE == "smoke"

# Keep max_tree_depth fixed at 4 unless deliberately testing something else.
SAMPLER_OVERRIDES = {
    # "seed": 44,
    # "num_warmup": 5,
    # "num_samples": 5,
    # "num_chains": 1,
    # "target_accept_prob": 0.8,
    # "progress_bar": True,
}

REQUIRE_VALID_INIT_BEFORE_NUTS = True
RUN_FIDUCIAL_WINDOWING_CHECK = False
RUN_FIDUCIAL_VALUE_CHECK = False
RUN_INITIALIZATION_DIAGNOSTIC = False
RUN_PHYSICAL_GRAD_DIAGNOSTIC = False
SAVE_OUTPUTS_AFTER_SAMPLING = True
OUTPUT_DIR = REPO_ROOT / "notebooks" / "xDESI" / "survey_measure" / "outputs" / "godmax_multiprobe_fast1024_true_nz_hmc_stage31_local"

print("config:", CONFIG)
print("run mode:", RUN_MODE)
print("output dir:", OUTPUT_DIR)

config: /mnt/ceph/users/spandey/ltu-godmax/GODMAX/param_files/xDESI/params_multiprobe_fast1024_hmc_stage31.yaml
run mode: smoke
output dir: /mnt/ceph/users/spandey/ltu-godmax/GODMAX/notebooks/xDESI/survey_measure/outputs/godmax_multiprobe_fast1024_true_nz_hmc_stage31_local

## Build Context And Static Checks

In [27]:

context = run_step("prepare_fit_context", lambda: hmc31.prepare_fit_context(CONFIG))
summary = hmc31.static_summary(context)
print(json.dumps(hmc31.gmt.to_jsonable(summary), indent=2))

settings = hmc31.sampler_settings(context.stage_config, smoke=SMOKE, overrides=SAMPLER_OVERRIDES)
print("sampler settings")
print(json.dumps(hmc31.gmt.to_jsonable(settings), indent=2))

[2026-06-04 00:15:21] START prepare_fit_context

[2026-06-04 00:15:22] DONE prepare_fit_context in 1.1 s
{
  "stage": "stage31_legacy_core",
  "n_parameters": 31,
  "n_spectra": 46,
  "data_vector_size": 460,
  "covariance_rank": 459,
  "covariance_size": 460,
  "dropped_covariance_modes": 1,
  "corr_eigenvalue_threshold": 1e-08,
  "min_corr_eigenvalue": -0.0036058517876595567,
  "max_corr_eigenvalue": 4.9400153738071,
  "parameter_names": [
    "log10_Mstar0_theta_ej",
    "theta_ej_0",
    "nu_theta_ej_M",
    "nu_theta_ej_z",
    "log10_Mc0",
    "mu_beta",
    "alpha_nt",
    "log10M1_fshmr_pz1",
    "log10M1_fshmr_pz2",
    "log10M1_fshmr_pz3",
    "log10M1_fshmr_pz4",
    "log10M1_a_fshmr_pz1",
    "log10M1_a_fshmr_pz2",
    "log10M1_a_fshmr_pz3",
    "log10M1_a_fshmr_pz4",
    "delta_fshmr_pz1",
    "delta_fshmr_pz2",
    "delta_fshmr_pz3",
    "delta_fshmr_pz4",
    "gamma_fshmr_pz1",
    "gamma_fshmr_pz2",
    "gamma_fshmr_pz3",
    "gamma_fshmr_pz4",
    "siglogMstar_Ncen_pz1",
    "siglogMstar_Ncen_pz2",
    "siglogMstar_Ncen_pz3",
    "siglogMstar_Ncen_pz4",
    "alphasat_Nsat_pz1",
    "alphasat_Nsat_pz2",
    "alphasat_Nsat_pz3",
    "alphasat_Nsat_pz4"
  ],
  "desi_lens_redshift_kind": "spectroscopic_calibrated_true_redshift",
  "desi_lens_nz_provenance": {
    "ksz_sigma_true_gas_calibration_json": "{\n  \"bin_assignment\": \"by_z_photo\",\n  \"c_km_s_convention\": 300000.0,\n  \"corrcoef_v_rec_v_true\": {\n    \"1\": 0.6871109287591863,\n    \"2\": 0.6683324285379622,\n    \"3\": 0.6210174474653414,\n    \"4\": 0.4660139572002138\n  },\n  \"description\": \"sigma_true_gas calibration for the DESI DR10 extended photometric tomographic bins in the ACTxDESI transfer package.\",\n  \"doc\": \"data/xDESI/survey_data/docs/DESI_ABACUS_SIGMA_TRUE_GAS.md\",\n  \"n_objects\": {\n    \"1\": 3279180,\n    \"2\": 3362292,\n    \"3\": 1304255,\n    \"4\": 360183\n  },\n  \"paper_definition\": \"Eq. 21-22: sigma_true denotes the velocity dispersion of the true line-of-sight velocities obtained from AbacusSummit. Eq. 37 notes the real-space stacking convention measures tau_bar * sigma_true / c.\",\n  \"path\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_abacus_velocity_calibration/sigma_true_gas_abacus_extended_lrg_zerr0p0_ph201_photometric_bins.json\",\n  \"sigma_true_gas_km_s\": {\n    \"1\": 316.74263812106005,\n    \"2\": 314.7475943710938,\n    \"3\": 310.7476445908045,\n    \"4\": 305.2816486132353\n  },\n  \"sigma_true_gas_over_c\": {\n    \"1\": 0.001055808793736867,\n    \"2\": 0.001049158647903646,\n    \"3\": 0.0010358254819693483,\n    \"4\": 0.001017605495377451\n  },\n  \"source\": \"json\",\n  \"source_npz_nersc\": \"/global/cfs/cdirs/desi/users/boryanah/kSZ_recon/for_fiona/Extended_LRG_zerr0.0_AbacusSummit_huge_c000_ph201.npz\",\n  \"std_convention\": \"Population standard deviation np.std(v_true, ddof=0), matching the earlier vr_rms=np.std(vr) convention.\",\n  \"velocity_column\": \"v_true\",\n  \"velocity_units\": \"km/s, true line-of-sight peculiar velocity. Values are not divided by c.\"\n}",
    "redshift_kind": "spectroscopic_calibrated_true_redshift",
    "selection_dataset": "catalog/valid_for_cl",
    "summary_json": "{\n  \"pz1\": {\n    \"alpha_galaxy_to_random\": 0.06702957924321741,\n    \"area_sr\": 5.61909441639038,\n    \"catalog_product_type\": \"Combined DESI DR9 Extended compact velocity catalog with imaging weights\",\n    \"desi_pz_bin\": 1,\n    \"desi_release\": \"DR9 Extended LRG\",\n    \"fsky_weighted\": 0.4471533260342989,\n    \"ksz_photoz_velocity_correlation_fracerr\": 0.1,\n    \"ksz_photoz_velocity_correlation_r\": 0.3,\n    \"ksz_sigma_rec_default\": \"weighted_rms_rec_vr_over_c\",\n    \"ksz_sigma_true_gas_bin_assignment\": \"by_z_photo\",\n    \"ksz_sigma_true_gas_calibration_doc\": \"data/xDESI/survey_data/docs/DESI_ABACUS_SIGMA_TRUE_GAS.md\",\n    \"ksz_sigma_true_gas_calibration_path\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_abacus_velocity_calibration/sigma_true_gas_abacus_extended_lrg_zerr0p0_ph201_photometric_bins.json\",\n    \"ksz_sigma_true_gas_calibration_source\": \"json\",\n    \"ksz_velocity_calibration_reference\": \"notebooks/xDESI/papers/ksz/2407.07152v2.pdf\",\n    \"mean_photoz\": 0.4712917668414762,\n    \"mean_photoz_unweighted\": 0.47129469487124837,\n    \"mean_true_z\": 0.46804403957102964,\n    \"mean_vr_over_c\": 5.914602176565046e-07,\n    \"mean_vr_over_c_unweighted\": 1.0783120090584099e-06,\n    \"mean_vr_over_c_weighted\": 5.914602176565046e-07,\n    \"mean_weight\": 1.0000119529852043,\n    \"mean_z\": 0.4712917668414762,\n    \"mean_z_convention\": \"catalog_z_phot_median\",\n    \"mean_z_unweighted\": 0.47129469487124837,\n    \"median_z\": 0.47070395946502686,\n    \"n_eff_per_sr\": 496135.27503421257,\n    \"n_excluded_by_random_mask\": 4729,\n    \"n_gal\": 2789662,\n    \"n_selected_before_random_mask\": 2794391,\n    \"nbar_per_sr\": 496467.07068159006,\n    \"random_count_dataset\": \"nside1024/random_count\",\n    \"random_count_derivation\": \"native\",\n    \"random_count_metadata\": {\n      \"random_count_dataset\": \"nside1024/random_count\",\n      \"random_count_derivation\": \"native\",\n      \"random_count_nside\": 1024,\n      \"random_count_ordering\": \"RING\",\n      \"random_count_source\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_imaging_randoms/desi_dr9_randoms_1_0_lrg_quality_count_maps_nside1024_4096.h5\"\n    },\n    \"random_count_ordering\": \"RING\",\n    \"random_count_source\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_imaging_randoms/desi_dr9_randoms_1_0_lrg_quality_count_maps_nside1024_4096.h5\",\n    \"random_counts_mean_valid\": 7.396949537464825,\n    \"random_counts_n_valid_pixels\": 5626491,\n    \"random_counts_sum_valid\": 41618870.0,\n    \"rms_rec_vr_over_c\": 0.00030257375084827314,\n    \"rms_rec_vr_over_c_unweighted\": 0.00030226860345031604,\n    \"rms_rec_vr_over_c_weighted\": 0.00030257375084827314,\n    \"selection_dataset\": \"catalog/valid_for_cl\",\n    \"shot_noise\": 2.0155793194326728e-06,\n    \"shot_noise_convention\": \"weighted Poisson: area_sr * sum(weight^2) / sum(weight)^2\",\n    \"sigma_rec_vr_over_c\": 0.00030257317276520713,\n    \"sigma_rec_vr_over_c_unweighted\": 0.0003022666800608621,\n    \"sigma_rec_vr_over_c_weighted\": 0.00030257317276520713,\n    \"sigma_true_gas_km_s\": 316.74263812106005,\n    \"sigma_true_gas_over_c\": 0.001055808793736867,\n    \"sigma_true_z\": 0.05817070673557862,\n    \"source_hdf5\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_extended_velocity_catalogs/desi_dr9_extended_all_pz_compact_with_weights.h5\",\n    \"sum_weight\": 2789695.344788611,\n    \"sum_weight2\": 2791560.982689174,\n    \"true_nz_dataset\": \"nz_unit_integral\",\n    \"true_nz_group\": \"zphot_std0p05_spec_ratio_corrected\",\n    \"true_nz_source_hdf5\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_redshift_distributions/desi_dr9_extended_lrg_sigmaz0p05_true_nz.h5\",\n    \"true_nz_surface_density_per_deg2\": 167.86608969615435,\n    \"weight_dataset\": \"catalog/weight_imaging_mean1\"\n  },\n  \"pz2\": {\n    \"alpha_galaxy_to_random\": 0.11377139532445142,\n    \"area_sr\": 5.61909441639038,\n    \"catalog_product_type\": \"Combined DESI DR9 Extended compact velocity catalog with imaging weights\",\n    \"desi_pz_bin\": 2,\n    \"desi_release\": \"DR9 Extended LRG\",\n    \"fsky_weighted\": 0.4471533260342989,\n    \"ksz_photoz_velocity_correlation_fracerr\": 0.1,\n    \"ksz_photoz_velocity_correlation_r\": 0.3,\n    \"ksz_sigma_rec_default\": \"weighted_rms_rec_vr_over_c\",\n    \"ksz_sigma_true_gas_bin_assignment\": \"by_z_photo\",\n    \"ksz_sigma_true_gas_calibration_doc\": \"data/xDESI/survey_data/docs/DESI_ABACUS_SIGMA_TRUE_GAS.md\",\n    \"ksz_sigma_true_gas_calibration_path\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_abacus_velocity_calibration/sigma_true_gas_abacus_extended_lrg_zerr0p0_ph201_photometric_bins.json\",\n    \"ksz_sigma_true_gas_calibration_source\": \"json\",\n    \"ksz_velocity_calibration_reference\": \"notebooks/xDESI/papers/ksz/2407.07152v2.pdf\",\n    \"mean_photoz\": 0.6349648788693658,\n    \"mean_photoz_unweighted\": 0.6349569992300919,\n    \"mean_true_z\": 0.6327928298079233,\n    \"mean_vr_over_c\": -9.191218281637348e-07,\n    \"mean_vr_over_c_unweighted\": -8.800304159362843e-07,\n    \"mean_vr_over_c_weighted\": -9.191218281637348e-07,\n    \"mean_weight\": 1.0000080067253456,\n    \"mean_z\": 0.6349648788693658,\n    \"mean_z_convention\": \"catalog_z_phot_median\",\n    \"mean_z_unweighted\": 0.6349569992300919,\n    \"median_z\": 0.6398811340332031,\n    \"n_eff_per_sr\": 842488.4227684836,\n    \"n_excluded_by_random_mask\": 8087,\n    \"n_gal\": 4734999,\n    \"n_selected_before_random_mask\": 4743086,\n    \"nbar_per_sr\": 842669.0425462222,\n    \"random_count_dataset\": \"nside1024/random_count\",\n    \"random_count_derivation\": \"native\",\n    \"random_count_metadata\": {\n      \"random_count_dataset\": \"nside1024/random_count\",\n      \"random_count_derivation\": \"native\",\n      \"random_count_nside\": 1024,\n      \"random_count_ordering\": \"RING\",\n      \"random_count_source\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_imaging_randoms/desi_dr9_randoms_1_0_lrg_quality_count_maps_nside1024_4096.h5\"\n    },\n    \"random_count_ordering\": \"RING\",\n    \"random_count_source\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_imaging_randoms/desi_dr9_randoms_1_0_lrg_quality_count_maps_nside1024_4096.h5\",\n    \"random_counts_mean_valid\": 7.396949537464825,\n    \"random_counts_n_valid_pixels\": 5626491,\n    \"random_counts_sum_valid\": 41618870.0,\n    \"rms_rec_vr_over_c\": 0.0002666112545455022,\n    \"rms_rec_vr_over_c_unweighted\": 0.0002665299538528901,\n    \"rms_rec_vr_over_c_weighted\": 0.0002666112545455022,\n    \"selection_dataset\": \"catalog/valid_for_cl\",\n    \"shot_noise\": 1.1869599308129612e-06,\n    \"shot_noise_convention\": \"weighted Poisson: area_sr * sum(weight^2) / sum(weight)^2\",\n    \"sigma_rec_vr_over_c\": 0.0002666096702398312,\n    \"sigma_rec_vr_over_c_unweighted\": 0.00026652850100372156,\n    \"sigma_rec_vr_over_c_weighted\": 0.0002666096702398312,\n    \"sigma_true_gas_km_s\": 314.7475943710938,\n    \"sigma_true_gas_over_c\": 0.001049158647903646,\n    \"sigma_true_z\": 0.07017092217658741,\n    \"source_hdf5\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_extended_velocity_catalogs/desi_dr9_extended_all_pz_compact_with_weights.h5\",\n    \"sum_weight\": 4735036.911836505,\n    \"sum_weight2\": 4736052.049008111,\n    \"true_nz_dataset\": \"nz_unit_integral\",\n    \"true_nz_group\": \"zphot_std0p05_spec_ratio_corrected\",\n    \"true_nz_source_hdf5\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_redshift_distributions/desi_dr9_extended_lrg_sigmaz0p05_true_nz.h5\",\n    \"true_nz_surface_density_per_deg2\": 284.75381734418113,\n    \"weight_dataset\": \"catalog/weight_imaging_mean1\"\n  },\n  \"pz3\": {\n    \"alpha_galaxy_to_random\": 0.14841909603070932,\n    \"area_sr\": 5.61909441639038,\n    \"catalog_product_type\": \"Combined DESI DR9 Extended compact velocity catalog with imaging weights\",\n    \"desi_pz_bin\": 3,\n    \"desi_release\": \"DR9 Extended LRG\",\n    \"fsky_weighted\": 0.4471533260342989,\n    \"ksz_photoz_velocity_correlation_fracerr\": 0.1,\n    \"ksz_photoz_velocity_correlation_r\": 0.3,\n    \"ksz_sigma_rec_default\": \"weighted_rms_rec_vr_over_c\",\n    \"ksz_sigma_true_gas_bin_assignment\": \"by_z_photo\",\n    \"ksz_sigma_true_gas_calibration_doc\": \"data/xDESI/survey_data/docs/DESI_ABACUS_SIGMA_TRUE_GAS.md\",\n    \"ksz_sigma_true_gas_calibration_path\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_abacus_velocity_calibration/sigma_true_gas_abacus_extended_lrg_zerr0p0_ph201_photometric_bins.json\",\n    \"ksz_sigma_true_gas_calibration_source\": \"json\",\n    \"ksz_velocity_calibration_reference\": \"notebooks/xDESI/papers/ksz/2407.07152v2.pdf\",\n    \"mean_photoz\": 0.7965062826337721,\n    \"mean_photoz_unweighted\": 0.7964977024079258,\n    \"mean_true_z\": 0.7912852093519888,\n    \"mean_vr_over_c\": 1.4039882366578035e-05,\n    \"mean_vr_over_c_unweighted\": 1.6179937893464924e-05,\n    \"mean_vr_over_c_weighted\": 1.4039882366578035e-05,\n    \"mean_weight\": 1.000015228119309,\n    \"mean_z\": 0.7965062826337721,\n    \"mean_z_convention\": \"catalog_z_phot_median\",\n    \"mean_z_unweighted\": 0.7964977024079258,\n    \"median_z\": 0.8029757738113403,\n    \"n_eff_per_sr\": 1098274.1110696914,\n    \"n_excluded_by_random_mask\": 10217,\n    \"n_gal\": 6176941,\n    \"n_selected_before_random_mask\": 6187158,\n    \"nbar_per_sr\": 1099293.6949371542,\n    \"random_count_dataset\": \"nside1024/random_count\",\n    \"random_count_derivation\": \"native\",\n    \"random_count_metadata\": {\n      \"random_count_dataset\": \"nside1024/random_count\",\n      \"random_count_derivation\": \"native\",\n      \"random_count_nside\": 1024,\n      \"random_count_ordering\": \"RING\",\n      \"random_count_source\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_imaging_randoms/desi_dr9_randoms_1_0_lrg_quality_count_maps_nside1024_4096.h5\"\n    },\n    \"random_count_ordering\": \"RING\",\n    \"random_count_source\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_imaging_randoms/desi_dr9_randoms_1_0_lrg_quality_count_maps_nside1024_4096.h5\",\n    \"random_counts_mean_valid\": 7.396949537464825,\n    \"random_counts_n_valid_pixels\": 5626491,\n    \"random_counts_sum_valid\": 41618870.0,\n    \"rms_rec_vr_over_c\": 0.00025260586354478606,\n    \"rms_rec_vr_over_c_unweighted\": 0.0002520345526630469,\n    \"rms_rec_vr_over_c_weighted\": 0.00025260586354478606,\n    \"selection_dataset\": \"catalog/valid_for_cl\",\n    \"shot_noise\": 9.105195050314217e-07,\n    \"shot_noise_convention\": \"weighted Poisson: area_sr * sum(weight^2) / sum(weight)^2\",\n    \"sigma_rec_vr_over_c\": 0.00025221539207657365,\n    \"sigma_rec_vr_over_c_unweighted\": 0.0002515146622879583,\n    \"sigma_rec_vr_over_c_weighted\": 0.00025221539207657365,\n    \"sigma_true_gas_km_s\": 310.7476445908045,\n    \"sigma_true_gas_over_c\": 0.0010358254819693483,\n    \"sigma_true_z\": 0.07479976820567019,\n    \"source_hdf5\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_extended_velocity_catalogs/desi_dr9_extended_all_pz_compact_with_weights.h5\",\n    \"sum_weight\": 6177035.063194513,\n    \"sum_weight2\": 6182769.519862213,\n    \"true_nz_dataset\": \"nz_unit_integral\",\n    \"true_nz_group\": \"zphot_std0p05_spec_ratio_corrected\",\n    \"true_nz_source_hdf5\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_redshift_distributions/desi_dr9_extended_lrg_sigmaz0p05_true_nz.h5\",\n    \"true_nz_surface_density_per_deg2\": 372.77728254673127,\n    \"weight_dataset\": \"catalog/weight_imaging_mean1\"\n  },\n  \"pz4\": {\n    \"alpha_galaxy_to_random\": 0.13582567035896004,\n    \"area_sr\": 5.61909441639038,\n    \"catalog_product_type\": \"Combined DESI DR9 Extended compact velocity catalog with imaging weights\",\n    \"desi_pz_bin\": 4,\n    \"desi_release\": \"DR9 Extended LRG\",\n    \"fsky_weighted\": 0.4471533260342989,\n    \"ksz_photoz_velocity_correlation_fracerr\": 0.1,\n    \"ksz_photoz_velocity_correlation_r\": 0.3,\n    \"ksz_sigma_rec_default\": \"weighted_rms_rec_vr_over_c\",\n    \"ksz_sigma_true_gas_bin_assignment\": \"by_z_photo\",\n    \"ksz_sigma_true_gas_calibration_doc\": \"data/xDESI/survey_data/docs/DESI_ABACUS_SIGMA_TRUE_GAS.md\",\n    \"ksz_sigma_true_gas_calibration_path\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_abacus_velocity_calibration/sigma_true_gas_abacus_extended_lrg_zerr0p0_ph201_photometric_bins.json\",\n    \"ksz_sigma_true_gas_calibration_source\": \"json\",\n    \"ksz_velocity_calibration_reference\": \"notebooks/xDESI/papers/ksz/2407.07152v2.pdf\",\n    \"mean_photoz\": 0.9181601877821283,\n    \"mean_photoz_unweighted\": 0.9181067181705124,\n    \"mean_true_z\": 0.9259410159482505,\n    \"mean_vr_over_c\": 2.999440095808183e-05,\n    \"mean_vr_over_c_unweighted\": 3.145041096829413e-05,\n    \"mean_vr_over_c_weighted\": 2.999440095808183e-05,\n    \"mean_weight\": 1.0000185602056522,\n    \"mean_z\": 0.9181601877821283,\n    \"mean_z_convention\": \"catalog_z_phot_median\",\n    \"mean_z_unweighted\": 0.9181067181705124,\n    \"median_z\": 0.9131101369857788,\n    \"n_eff_per_sr\": 1004329.9150819988,\n    \"n_excluded_by_random_mask\": 9133,\n    \"n_gal\": 5652806,\n    \"n_selected_before_random_mask\": 5661939,\n    \"nbar_per_sr\": 1006018.1407083767,\n    \"random_count_dataset\": \"nside1024/random_count\",\n    \"random_count_derivation\": \"native\",\n    \"random_count_metadata\": {\n      \"random_count_dataset\": \"nside1024/random_count\",\n      \"random_count_derivation\": \"native\",\n      \"random_count_nside\": 1024,\n      \"random_count_ordering\": \"RING\",\n      \"random_count_source\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_imaging_randoms/desi_dr9_randoms_1_0_lrg_quality_count_maps_nside1024_4096.h5\"\n    },\n    \"random_count_ordering\": \"RING\",\n    \"random_count_source\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_imaging_randoms/desi_dr9_randoms_1_0_lrg_quality_count_maps_nside1024_4096.h5\",\n    \"random_counts_mean_valid\": 7.396949537464825,\n    \"random_counts_n_valid_pixels\": 5626491,\n    \"random_counts_sum_valid\": 41618870.0,\n    \"rms_rec_vr_over_c\": 0.00024381628559913456,\n    \"rms_rec_vr_over_c_unweighted\": 0.00024428266436384325,\n    \"rms_rec_vr_over_c_weighted\": 0.00024381628559913456,\n    \"selection_dataset\": \"catalog/valid_for_cl\",\n    \"shot_noise\": 9.956887522546362e-07,\n    \"shot_noise_convention\": \"weighted Poisson: area_sr * sum(weight^2) / sum(weight)^2\",\n    \"sigma_rec_vr_over_c\": 0.00024196428875874337,\n    \"sigma_rec_vr_over_c_unweighted\": 0.00024224964759236202,\n    \"sigma_rec_vr_over_c_weighted\": 0.00024196428875874337,\n    \"sigma_true_gas_km_s\": 305.2816486132353,\n    \"sigma_true_gas_over_c\": 0.001017605495377451,\n    \"sigma_true_z\": 0.08839465546891845,\n    \"source_hdf5\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_extended_velocity_catalogs/desi_dr9_extended_all_pz_compact_with_weights.h5\",\n    \"sum_weight\": 5652910.917241871,\n    \"sum_weight2\": 5662413.162401361,\n    \"true_nz_dataset\": \"nz_unit_integral\",\n    \"true_nz_group\": \"zphot_std0p05_spec_ratio_corrected\",\n    \"true_nz_source_hdf5\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_redshift_distributions/desi_dr9_extended_lrg_sigmaz0p05_true_nz.h5\",\n    \"true_nz_surface_density_per_deg2\": 341.29743556463285,\n    \"weight_dataset\": \"catalog/weight_imaging_mean1\"\n  }\n}",
    "theory_nz_dataset": "nz_unit_integral",
    "theory_nz_group": "zphot_std0p05_spec_ratio_corrected",
    "theory_nz_note": "Primary nz/desi/* arrays are calibrated true-redshift kernels for theory. Catalog Z_PHOT_MEDIAN histograms are saved only under nz/desi_photoz_diagnostic.",
    "theory_nz_sample": "full_valid_for_cl_dr9_extended_lrg",
    "theory_nz_source_hdf5": "/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_redshift_distributions/desi_dr9_extended_lrg_sigmaz0p05_true_nz.h5",

In [28]:
spec_rows = [
    {
        "i": i,
        "name": spec.name,
        "target": spec.target,
        "fiducial": spec.fiducial,
        "prior_min": spec.prior_min,
        "prior_max": spec.prior_max,
        "inside_prior": spec.prior_min <= spec.fiducial <= spec.prior_max,
    }
    for i, spec in enumerate(context.parameter_specs)
]
spec_table = pd.DataFrame(spec_rows)
spec_table

,i,name,target,fiducial,prior_min,prior_max,inside_prior
0,0,log10_Mstar0_theta_ej,sim_scalar,15.0000,14.000,16.5,True
1,1,theta_ej_0,sim_scalar,2.0000,0.500,8.0,True
2,2,nu_theta_ej_M,sim_scalar,-0.3300,-1.000,1.0,True
3,3,nu_theta_ej_z,sim_scalar,-1.2200,-2.000,2.0,True
4,4,log10_Mc0,sim_scalar,13.7500,13.000,16.0,True
5,5,mu_beta,sim_scalar,0.0762,0.005,1.5,True
6,6,alpha_nt,sim_scalar,0.0500,0.000,0.5,True
7,7,log10M1_fshmr_pz1,hod_array,14.5913,11.000,15.5,True
8,8,log10M1_fshmr_pz2,hod_array,14.6232,11.000,15.5,True
9,9,log10M1_fshmr_pz3,hod_array,14.5384,11.000,15.5,True
10,10,log10M1_fshmr_pz4,hod_array,13.7882,11.000,15.5,True
11,11,log10M1_a_fshmr_pz1,hod_array,-1.2424,-3.000,3.0,True
12,12,log10M1_a_fshmr_pz2,hod_array,-0.6887,-3.000,3.0,True
13,13,log10M1_a_fshmr_pz3,hod_array,-1.3134,-3.000,3.0,True
14,14,log10M1_a_fshmr_pz4,hod_array,-2.4661,-3.000,3.0,True
15,15,delta_fshmr_pz1,hod_array,0.5337,0.001,1.5,True
16,16,delta_fshmr_pz2,hod_array,0.8247,0.001,1.5,True
17,17,delta_fshmr_pz3,hod_array,0.5177,0.001,1.5,True
18,18,delta_fshmr_pz4,hod_array,0.4893,0.001,1.5,True
19,19,gamma_fshmr_pz1,hod_array,0.6581,0.010,3.0,True
20,20,gamma_fshmr_pz2,hod_array,1.8305,0.010,3.0,True
21,21,gamma_fshmr_pz3,hod_array,1.7547,0.010,3.0,True
22,22,gamma_fshmr_pz4,hod_array,1.8496,0.010,3.0,True
23,23,siglogMstar_Ncen_pz1,hod_array,0.2277,0.050,1.0,True
24,24,siglogMstar_Ncen_pz2,hod_array,0.2180,0.050,1.0,True
25,25,siglogMstar_Ncen_pz3,hod_array,0.2525,0.050,1.0,True
26,26,siglogMstar_Ncen_pz4,hod_array,0.2338,0.050,1.0,True
27,27,alphasat_Nsat_pz1,hod_array,0.9053,0.400,2.2,True
28,28,alphasat_Nsat_pz2,hod_array,1.6872,0.400,2.2,True
29,29,alphasat_Nsat_pz3,hod_array,1.0483,0.400,2.2,True
30,30,alphasat_Nsat_pz4,hod_array,1.1953,0.400,2.2,True

## DESI true n(z), photo-z diagnostic, and HOD number-density targets

This cell shows the calibrated true-redshift DESI `dN/dz` used in theory, the catalog `Z_PHOT_MEDIAN` histogram saved only as a diagnostic, the per-pz comoving number density target, and the corresponding physical/proper number density. Each pz bin is fit with its own single-pz GODMAX galaxy object; no HOD parameter is assigned by true-redshift support intervals.

In [29]:
import matplotlib.pyplot as plt

md_nbar = context.config["metadata"]
z_nbar = np.asarray(md_nbar["lens_z_mid"])
dndz_pz = np.asarray(md_nbar["lens_dndz"])
photoz = md_nbar.get("lens_photoz_diagnostic") or {}
z_photo = None if photoz.get("z_mid") is None else np.asarray(photoz["z_mid"])
dndz_photo = None if photoz.get("dndz_by_pz") is None else np.asarray(photoz["dndz_by_pz"])
nbar_comoving_by_pz = np.asarray(md_nbar["nbar_comoving_by_pz"])
nbar_physical_by_pz = np.asarray(md_nbar["nbar_physical_by_pz"])
nbar_sum = np.asarray(md_nbar["nbar_comoving_sum_by_pz"])
nbar_per_sr = np.asarray(md_nbar["nbar_per_sr_by_pz"])
chi = np.asarray(md_nbar["chi_lens_hmpc"])
dchi_dz = np.asarray(md_nbar["dchi_dz_lens_hmpc"])

rows = []
for i in range(4):
    mask = dndz_pz[i] > 0
    recovered_nbar_sr = np.trapz(nbar_comoving_by_pz[i] * chi**2 * dchi_dz, z_nbar)
    rows.append(
        {
            "pz": i + 1,
            "nbar_per_sr_measured": nbar_per_sr[i],
            "nbar_per_sr_recovered": recovered_nbar_sr,
            "fractional_recovery_error": (recovered_nbar_sr / nbar_per_sr[i] - 1.0),
            "true_dndz_integral": np.trapz(dndz_pz[i], z_nbar),
            "true_mean_z": np.trapz(z_nbar * dndz_pz[i], z_nbar),
            "photoz_mean_z": np.trapz(z_photo * dndz_photo[i], z_photo) if z_photo is not None else np.nan,
            "z_support_min": z_nbar[mask][0] if np.any(mask) else np.nan,
            "z_support_max": z_nbar[mask][-1] if np.any(mask) else np.nan,
            "comoving_median": np.median(nbar_comoving_by_pz[i, mask]) if np.any(mask) else np.nan,
            "physical_median": np.median(nbar_physical_by_pz[i, mask]) if np.any(mask) else np.nan,
        }
    )
nbar_summary_table = pd.DataFrame(rows)
display(nbar_summary_table)
print("nbar target convention:", md_nbar.get("nbar_target_convention"))
print("DESI lens redshift kind:", md_nbar.get("lens_redshift_kind"))
print("DESI lens n(z) provenance:", json.dumps(hmc31.gmt.to_jsonable(md_nbar.get("lens_nz_provenance", {})), indent=2))

colors = plt.rcParams["axes.prop_cycle"].by_key()["color"]
fig, axes = plt.subplots(2, 2, figsize=(14, 8), constrained_layout=True)
axes = axes.ravel()

for i in range(4):
    color = colors[i % len(colors)]
    axes[0].plot(z_nbar, dndz_pz[i], color=color, lw=2.0, label=f"pz{i + 1} true")
    if z_photo is not None:
        axes[1].plot(z_photo, dndz_photo[i], color=color, lw=1.6, label=f"pz{i + 1} photo-z")
    axes[2].plot(z_nbar, nbar_comoving_by_pz[i], color=color, label=f"pz{i + 1}")
    axes[3].plot(z_nbar, nbar_physical_by_pz[i], color=color, label=f"pz{i + 1}")

axes[2].plot(z_nbar, nbar_sum, color="0.45", ls=":", lw=2.0, label="sum over pz")
axes[0].set_ylabel("true normalized dN/dz")
axes[1].set_ylabel("photo-z diagnostic dN/dz")
axes[2].set_ylabel("comoving nbar [(Mpc/h)^-3]")
axes[3].set_ylabel("physical nbar [(Mpc/h)^-3 proper]")
for ax in axes:
    ax.set_xlabel("z")
    ax.grid(True, alpha=0.25)
    ax.legend(fontsize=9)
plt.show()

,pz,nbar_per_sr_measured,nbar_per_sr_recovered,fractional_recovery_error,true_dndz_integral,true_mean_z,photoz_mean_z,z_support_min,z_support_max,comoving_median,physical_median
0,1,4.964671e+05,4.964677e+05,1.318276e-06,1.0,0.468044,0.471306,0.07,1.05,0.000018,0.000033
1,2,8.426690e+05,8.426695e+05,5.111347e-07,1.0,0.632793,0.634992,0.07,1.39,0.000013,0.000033
2,3,1.099294e+06,1.099294e+06,2.689364e-07,1.0,0.791285,0.796454,0.05,1.41,0.000009,0.000046
3,4,1.006018e+06,1.006018e+06,1.114246e-07,1.0,0.925941,0.918186,0.09,1.43,0.000006,0.000040

nbar target convention: per_photoz_bin_single_godmax_models
DESI lens redshift kind: spectroscopic_calibrated_true_redshift
DESI lens n(z) provenance: {
  "ksz_sigma_true_gas_calibration_json": "{\n  \"bin_assignment\": \"by_z_photo\",\n  \"c_km_s_convention\": 300000.0,\n  \"corrcoef_v_rec_v_true\": {\n    \"1\": 0.6871109287591863,\n    \"2\": 0.6683324285379622,\n    \"3\": 0.6210174474653414,\n    \"4\": 0.4660139572002138\n  },\n  \"description\": \"sigma_true_gas calibration for the DESI DR10 extended photometric tomographic bins in the ACTxDESI transfer package.\",\n  \"doc\": \"data/xDESI/survey_data/docs/DESI_ABACUS_SIGMA_TRUE_GAS.md\",\n  \"n_objects\": {\n    \"1\": 3279180,\n    \"2\": 3362292,\n    \"3\": 1304255,\n    \"4\": 360183\n  },\n  \"paper_definition\": \"Eq. 21-22: sigma_true denotes the velocity dispersion of the true line-of-sight velocities obtained from AbacusSummit. Eq. 37 notes the real-space stacking convention measures tau_bar * sigma_true / c.\",\n  \"path\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_abacus_velocity_calibration/sigma_true_gas_abacus_extended_lrg_zerr0p0_ph201_photometric_bins.json\",\n  \"sigma_true_gas_km_s\": {\n    \"1\": 316.74263812106005,\n    \"2\": 314.7475943710938,\n    \"3\": 310.7476445908045,\n    \"4\": 305.2816486132353\n  },\n  \"sigma_true_gas_over_c\": {\n    \"1\": 0.001055808793736867,\n    \"2\": 0.001049158647903646,\n    \"3\": 0.0010358254819693483,\n    \"4\": 0.001017605495377451\n  },\n  \"source\": \"json\",\n  \"source_npz_nersc\": \"/global/cfs/cdirs/desi/users/boryanah/kSZ_recon/for_fiona/Extended_LRG_zerr0.0_AbacusSummit_huge_c000_ph201.npz\",\n  \"std_convention\": \"Population standard deviation np.std(v_true, ddof=0), matching the earlier vr_rms=np.std(vr) convention.\",\n  \"velocity_column\": \"v_true\",\n  \"velocity_units\": \"km/s, true line-of-sight peculiar velocity. Values are not divided by c.\"\n}",
  "redshift_kind": "spectroscopic_calibrated_true_redshift",
  "selection_dataset": "catalog/valid_for_cl",
  "summary_json": "{\n  \"pz1\": {\n    \"alpha_galaxy_to_random\": 0.06702957924321741,\n    \"area_sr\": 5.61909441639038,\n    \"catalog_product_type\": \"Combined DESI DR9 Extended compact velocity catalog with imaging weights\",\n    \"desi_pz_bin\": 1,\n    \"desi_release\": \"DR9 Extended LRG\",\n    \"fsky_weighted\": 0.4471533260342989,\n    \"ksz_photoz_velocity_correlation_fracerr\": 0.1,\n    \"ksz_photoz_velocity_correlation_r\": 0.3,\n    \"ksz_sigma_rec_default\": \"weighted_rms_rec_vr_over_c\",\n    \"ksz_sigma_true_gas_bin_assignment\": \"by_z_photo\",\n    \"ksz_sigma_true_gas_calibration_doc\": \"data/xDESI/survey_data/docs/DESI_ABACUS_SIGMA_TRUE_GAS.md\",\n    \"ksz_sigma_true_gas_calibration_path\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_abacus_velocity_calibration/sigma_true_gas_abacus_extended_lrg_zerr0p0_ph201_photometric_bins.json\",\n    \"ksz_sigma_true_gas_calibration_source\": \"json\",\n    \"ksz_velocity_calibration_reference\": \"notebooks/xDESI/papers/ksz/2407.07152v2.pdf\",\n    \"mean_photoz\": 0.4712917668414762,\n    \"mean_photoz_unweighted\": 0.47129469487124837,\n    \"mean_true_z\": 0.46804403957102964,\n    \"mean_vr_over_c\": 5.914602176565046e-07,\n    \"mean_vr_over_c_unweighted\": 1.0783120090584099e-06,\n    \"mean_vr_over_c_weighted\": 5.914602176565046e-07,\n    \"mean_weight\": 1.0000119529852043,\n    \"mean_z\": 0.4712917668414762,\n    \"mean_z_convention\": \"catalog_z_phot_median\",\n    \"mean_z_unweighted\": 0.47129469487124837,\n    \"median_z\": 0.47070395946502686,\n    \"n_eff_per_sr\": 496135.27503421257,\n    \"n_excluded_by_random_mask\": 4729,\n    \"n_gal\": 2789662,\n    \"n_selected_before_random_mask\": 2794391,\n    \"nbar_per_sr\": 496467.07068159006,\n    \"random_count_dataset\": \"nside1024/random_count\",\n    \"random_count_derivation\": \"native\",\n    \"random_count_metadata\": {\n      \"random_count_dataset\": \"nside1024/random_count\",\n      \"random_count_derivation\": \"native\",\n      \"random_count_nside\": 1024,\n      \"random_count_ordering\": \"RING\",\n      \"random_count_source\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_imaging_randoms/desi_dr9_randoms_1_0_lrg_quality_count_maps_nside1024_4096.h5\"\n    },\n    \"random_count_ordering\": \"RING\",\n    \"random_count_source\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_imaging_randoms/desi_dr9_randoms_1_0_lrg_quality_count_maps_nside1024_4096.h5\",\n    \"random_counts_mean_valid\": 7.396949537464825,\n    \"random_counts_n_valid_pixels\": 5626491,\n    \"random_counts_sum_valid\": 41618870.0,\n    \"rms_rec_vr_over_c\": 0.00030257375084827314,\n    \"rms_rec_vr_over_c_unweighted\": 0.00030226860345031604,\n    \"rms_rec_vr_over_c_weighted\": 0.00030257375084827314,\n    \"selection_dataset\": \"catalog/valid_for_cl\",\n    \"shot_noise\": 2.0155793194326728e-06,\n    \"shot_noise_convention\": \"weighted Poisson: area_sr * sum(weight^2) / sum(weight)^2\",\n    \"sigma_rec_vr_over_c\": 0.00030257317276520713,\n    \"sigma_rec_vr_over_c_unweighted\": 0.0003022666800608621,\n    \"sigma_rec_vr_over_c_weighted\": 0.00030257317276520713,\n    \"sigma_true_gas_km_s\": 316.74263812106005,\n    \"sigma_true_gas_over_c\": 0.001055808793736867,\n    \"sigma_true_z\": 0.05817070673557862,\n    \"source_hdf5\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_extended_velocity_catalogs/desi_dr9_extended_all_pz_compact_with_weights.h5\",\n    \"sum_weight\": 2789695.344788611,\n    \"sum_weight2\": 2791560.982689174,\n    \"true_nz_dataset\": \"nz_unit_integral\",\n    \"true_nz_group\": \"zphot_std0p05_spec_ratio_corrected\",\n    \"true_nz_source_hdf5\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_redshift_distributions/desi_dr9_extended_lrg_sigmaz0p05_true_nz.h5\",\n    \"true_nz_surface_density_per_deg2\": 167.86608969615435,\n    \"weight_dataset\": \"catalog/weight_imaging_mean1\"\n  },\n  \"pz2\": {\n    \"alpha_galaxy_to_random\": 0.11377139532445142,\n    \"area_sr\": 5.61909441639038,\n    \"catalog_product_type\": \"Combined DESI DR9 Extended compact velocity catalog with imaging weights\",\n    \"desi_pz_bin\": 2,\n    \"desi_release\": \"DR9 Extended LRG\",\n    \"fsky_weighted\": 0.4471533260342989,\n    \"ksz_photoz_velocity_correlation_fracerr\": 0.1,\n    \"ksz_photoz_velocity_correlation_r\": 0.3,\n    \"ksz_sigma_rec_default\": \"weighted_rms_rec_vr_over_c\",\n    \"ksz_sigma_true_gas_bin_assignment\": \"by_z_photo\",\n    \"ksz_sigma_true_gas_calibration_doc\": \"data/xDESI/survey_data/docs/DESI_ABACUS_SIGMA_TRUE_GAS.md\",\n    \"ksz_sigma_true_gas_calibration_path\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_abacus_velocity_calibration/sigma_true_gas_abacus_extended_lrg_zerr0p0_ph201_photometric_bins.json\",\n    \"ksz_sigma_true_gas_calibration_source\": \"json\",\n    \"ksz_velocity_calibration_reference\": \"notebooks/xDESI/papers/ksz/2407.07152v2.pdf\",\n    \"mean_photoz\": 0.6349648788693658,\n    \"mean_photoz_unweighted\": 0.6349569992300919,\n    \"mean_true_z\": 0.6327928298079233,\n    \"mean_vr_over_c\": -9.191218281637348e-07,\n    \"mean_vr_over_c_unweighted\": -8.800304159362843e-07,\n    \"mean_vr_over_c_weighted\": -9.191218281637348e-07,\n    \"mean_weight\": 1.0000080067253456,\n    \"mean_z\": 0.6349648788693658,\n    \"mean_z_convention\": \"catalog_z_phot_median\",\n    \"mean_z_unweighted\": 0.6349569992300919,\n    \"median_z\": 0.6398811340332031,\n    \"n_eff_per_sr\": 842488.4227684836,\n    \"n_excluded_by_random_mask\": 8087,\n    \"n_gal\": 4734999,\n    \"n_selected_before_random_mask\": 4743086,\n    \"nbar_per_sr\": 842669.0425462222,\n    \"random_count_dataset\": \"nside1024/random_count\",\n    \"random_count_derivation\": \"native\",\n    \"random_count_metadata\": {\n      \"random_count_dataset\": \"nside1024/random_count\",\n      \"random_count_derivation\": \"native\",\n      \"random_count_nside\": 1024,\n      \"random_count_ordering\": \"RING\",\n      \"random_count_source\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_imaging_randoms/desi_dr9_randoms_1_0_lrg_quality_count_maps_nside1024_4096.h5\"\n    },\n    \"random_count_ordering\": \"RING\",\n    \"random_count_source\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_imaging_randoms/desi_dr9_randoms_1_0_lrg_quality_count_maps_nside1024_4096.h5\",\n    \"random_counts_mean_valid\": 7.396949537464825,\n    \"random_counts_n_valid_pixels\": 5626491,\n    \"random_counts_sum_valid\": 41618870.0,\n    \"rms_rec_vr_over_c\": 0.0002666112545455022,\n    \"rms_rec_vr_over_c_unweighted\": 0.0002665299538528901,\n    \"rms_rec_vr_over_c_weighted\": 0.0002666112545455022,\n    \"selection_dataset\": \"catalog/valid_for_cl\",\n    \"shot_noise\": 1.1869599308129612e-06,\n    \"shot_noise_convention\": \"weighted Poisson: area_sr * sum(weight^2) / sum(weight)^2\",\n    \"sigma_rec_vr_over_c\": 0.0002666096702398312,\n    \"sigma_rec_vr_over_c_unweighted\": 0.00026652850100372156,\n    \"sigma_rec_vr_over_c_weighted\": 0.0002666096702398312,\n    \"sigma_true_gas_km_s\": 314.7475943710938,\n    \"sigma_true_gas_over_c\": 0.001049158647903646,\n    \"sigma_true_z\": 0.07017092217658741,\n    \"source_hdf5\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_extended_velocity_catalogs/desi_dr9_extended_all_pz_compact_with_weights.h5\",\n    \"sum_weight\": 4735036.911836505,\n    \"sum_weight2\": 4736052.049008111,\n    \"true_nz_dataset\": \"nz_unit_integral\",\n    \"true_nz_group\": \"zphot_std0p05_spec_ratio_corrected\",\n    \"true_nz_source_hdf5\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_redshift_distributions/desi_dr9_extended_lrg_sigmaz0p05_true_nz.h5\",\n    \"true_nz_surface_density_per_deg2\": 284.75381734418113,\n    \"weight_dataset\": \"catalog/weight_imaging_mean1\"\n  },\n  \"pz3\": {\n    \"alpha_galaxy_to_random\": 0.14841909603070932,\n    \"area_sr\": 5.61909441639038,\n    \"catalog_product_type\": \"Combined DESI DR9 Extended compact velocity catalog with imaging weights\",\n    \"desi_pz_bin\": 3,\n    \"desi_release\": \"DR9 Extended LRG\",\n    \"fsky_weighted\": 0.4471533260342989,\n    \"ksz_photoz_velocity_correlation_fracerr\": 0.1,\n    \"ksz_photoz_velocity_correlation_r\": 0.3,\n    \"ksz_sigma_rec_default\": \"weighted_rms_rec_vr_over_c\",\n    \"ksz_sigma_true_gas_bin_assignment\": \"by_z_photo\",\n    \"ksz_sigma_true_gas_calibration_doc\": \"data/xDESI/survey_data/docs/DESI_ABACUS_SIGMA_TRUE_GAS.md\",\n    \"ksz_sigma_true_gas_calibration_path\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_abacus_velocity_calibration/sigma_true_gas_abacus_extended_lrg_zerr0p0_ph201_photometric_bins.json\",\n    \"ksz_sigma_true_gas_calibration_source\": \"json\",\n    \"ksz_velocity_calibration_reference\": \"notebooks/xDESI/papers/ksz/2407.07152v2.pdf\",\n    \"mean_photoz\": 0.7965062826337721,\n    \"mean_photoz_unweighted\": 0.7964977024079258,\n    \"mean_true_z\": 0.7912852093519888,\n    \"mean_vr_over_c\": 1.4039882366578035e-05,\n    \"mean_vr_over_c_unweighted\": 1.6179937893464924e-05,\n    \"mean_vr_over_c_weighted\": 1.4039882366578035e-05,\n    \"mean_weight\": 1.000015228119309,\n    \"mean_z\": 0.7965062826337721,\n    \"mean_z_convention\": \"catalog_z_phot_median\",\n    \"mean_z_unweighted\": 0.7964977024079258,\n    \"median_z\": 0.8029757738113403,\n    \"n_eff_per_sr\": 1098274.1110696914,\n    \"n_excluded_by_random_mask\": 10217,\n    \"n_gal\": 6176941,\n    \"n_selected_before_random_mask\": 6187158,\n    \"nbar_per_sr\": 1099293.6949371542,\n    \"random_count_dataset\": \"nside1024/random_count\",\n    \"random_count_derivation\": \"native\",\n    \"random_count_metadata\": {\n      \"random_count_dataset\": \"nside1024/random_count\",\n      \"random_count_derivation\": \"native\",\n      \"random_count_nside\": 1024,\n      \"random_count_ordering\": \"RING\",\n      \"random_count_source\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_imaging_randoms/desi_dr9_randoms_1_0_lrg_quality_count_maps_nside1024_4096.h5\"\n    },\n    \"random_count_ordering\": \"RING\",\n    \"random_count_source\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_imaging_randoms/desi_dr9_randoms_1_0_lrg_quality_count_maps_nside1024_4096.h5\",\n    \"random_counts_mean_valid\": 7.396949537464825,\n    \"random_counts_n_valid_pixels\": 5626491,\n    \"random_counts_sum_valid\": 41618870.0,\n    \"rms_rec_vr_over_c\": 0.00025260586354478606,\n    \"rms_rec_vr_over_c_unweighted\": 0.0002520345526630469,\n    \"rms_rec_vr_over_c_weighted\": 0.00025260586354478606,\n    \"selection_dataset\": \"catalog/valid_for_cl\",\n    \"shot_noise\": 9.105195050314217e-07,\n    \"shot_noise_convention\": \"weighted Poisson: area_sr * sum(weight^2) / sum(weight)^2\",\n    \"sigma_rec_vr_over_c\": 0.00025221539207657365,\n    \"sigma_rec_vr_over_c_unweighted\": 0.0002515146622879583,\n    \"sigma_rec_vr_over_c_weighted\": 0.00025221539207657365,\n    \"sigma_true_gas_km_s\": 310.7476445908045,\n    \"sigma_true_gas_over_c\": 0.0010358254819693483,\n    \"sigma_true_z\": 0.07479976820567019,\n    \"source_hdf5\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_extended_velocity_catalogs/desi_dr9_extended_all_pz_compact_with_weights.h5\",\n    \"sum_weight\": 6177035.063194513,\n    \"sum_weight2\": 6182769.519862213,\n    \"true_nz_dataset\": \"nz_unit_integral\",\n    \"true_nz_group\": \"zphot_std0p05_spec_ratio_corrected\",\n    \"true_nz_source_hdf5\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_redshift_distributions/desi_dr9_extended_lrg_sigmaz0p05_true_nz.h5\",\n    \"true_nz_surface_density_per_deg2\": 372.77728254673127,\n    \"weight_dataset\": \"catalog/weight_imaging_mean1\"\n  },\n  \"pz4\": {\n    \"alpha_galaxy_to_random\": 0.13582567035896004,\n    \"area_sr\": 5.61909441639038,\n    \"catalog_product_type\": \"Combined DESI DR9 Extended compact velocity catalog with imaging weights\",\n    \"desi_pz_bin\": 4,\n    \"desi_release\": \"DR9 Extended LRG\",\n    \"fsky_weighted\": 0.4471533260342989,\n    \"ksz_photoz_velocity_correlation_fracerr\": 0.1,\n    \"ksz_photoz_velocity_correlation_r\": 0.3,\n    \"ksz_sigma_rec_default\": \"weighted_rms_rec_vr_over_c\",\n    \"ksz_sigma_true_gas_bin_assignment\": \"by_z_photo\",\n    \"ksz_sigma_true_gas_calibration_doc\": \"data/xDESI/survey_data/docs/DESI_ABACUS_SIGMA_TRUE_GAS.md\",\n    \"ksz_sigma_true_gas_calibration_path\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_abacus_velocity_calibration/sigma_true_gas_abacus_extended_lrg_zerr0p0_ph201_photometric_bins.json\",\n    \"ksz_sigma_true_gas_calibration_source\": \"json\",\n    \"ksz_velocity_calibration_reference\": \"notebooks/xDESI/papers/ksz/2407.07152v2.pdf\",\n    \"mean_photoz\": 0.9181601877821283,\n    \"mean_photoz_unweighted\": 0.9181067181705124,\n    \"mean_true_z\": 0.9259410159482505,\n    \"mean_vr_over_c\": 2.999440095808183e-05,\n    \"mean_vr_over_c_unweighted\": 3.145041096829413e-05,\n    \"mean_vr_over_c_weighted\": 2.999440095808183e-05,\n    \"mean_weight\": 1.0000185602056522,\n    \"mean_z\": 0.9181601877821283,\n    \"mean_z_convention\": \"catalog_z_phot_median\",\n    \"mean_z_unweighted\": 0.9181067181705124,\n    \"median_z\": 0.9131101369857788,\n    \"n_eff_per_sr\": 1004329.9150819988,\n    \"n_excluded_by_random_mask\": 9133,\n    \"n_gal\": 5652806,\n    \"n_selected_before_random_mask\": 5661939,\n    \"nbar_per_sr\": 1006018.1407083767,\n    \"random_count_dataset\": \"nside1024/random_count\",\n    \"random_count_derivation\": \"native\",\n    \"random_count_metadata\": {\n      \"random_count_dataset\": \"nside1024/random_count\",\n      \"random_count_derivation\": \"native\",\n      \"random_count_nside\": 1024,\n      \"random_count_ordering\": \"RING\",\n      \"random_count_source\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_imaging_randoms/desi_dr9_randoms_1_0_lrg_quality_count_maps_nside1024_4096.h5\"\n    },\n    \"random_count_ordering\": \"RING\",\n    \"random_count_source\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_imaging_randoms/desi_dr9_randoms_1_0_lrg_quality_count_maps_nside1024_4096.h5\",\n    \"random_counts_mean_valid\": 7.396949537464825,\n    \"random_counts_n_valid_pixels\": 5626491,\n    \"random_counts_sum_valid\": 41618870.0,\n    \"rms_rec_vr_over_c\": 0.00024381628559913456,\n    \"rms_rec_vr_over_c_unweighted\": 0.00024428266436384325,\n    \"rms_rec_vr_over_c_weighted\": 0.00024381628559913456,\n    \"selection_dataset\": \"catalog/valid_for_cl\",\n    \"shot_noise\": 9.956887522546362e-07,\n    \"shot_noise_convention\": \"weighted Poisson: area_sr * sum(weight^2) / sum(weight)^2\",\n    \"sigma_rec_vr_over_c\": 0.00024196428875874337,\n    \"sigma_rec_vr_over_c_unweighted\": 0.00024224964759236202,\n    \"sigma_rec_vr_over_c_weighted\": 0.00024196428875874337,\n    \"sigma_true_gas_km_s\": 305.2816486132353,\n    \"sigma_true_gas_over_c\": 0.001017605495377451,\n    \"sigma_true_z\": 0.08839465546891845,\n    \"source_hdf5\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_extended_velocity_catalogs/desi_dr9_extended_all_pz_compact_with_weights.h5\",\n    \"sum_weight\": 5652910.917241871,\n    \"sum_weight2\": 5662413.162401361,\n    \"true_nz_dataset\": \"nz_unit_integral\",\n    \"true_nz_group\": \"zphot_std0p05_spec_ratio_corrected\",\n    \"true_nz_source_hdf5\": \"/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_redshift_distributions/desi_dr9_extended_lrg_sigmaz0p05_true_nz.h5\",\n    \"true_nz_surface_density_per_deg2\": 341.29743556463285,\n    \"weight_dataset\": \"catalog/weight_imaging_mean1\"\n  }\n}",
  "theory_nz_dataset": "nz_unit_integral",
  "theory_nz_group": "zphot_std0p05_spec_ratio_corrected",
  "theory_nz_note": "Primary nz/desi/* arrays are calibrated true-redshift kernels for theory. Catalog Z_PHOT_MEDIAN histograms are saved only under nz/desi_photoz_diagnostic.",
  "theory_nz_sample": "full_valid_for_cl_dr9_extended_lrg",
  "theory_nz_source_hdf5": "/mnt/ceph/users/spandey/ltu-godmax/GODMAX/data/xDESI/survey_data/data/desi_dr9_redshift_distributions/desi_dr9_extended_lrg_sigmaz0p05_true_nz.h5",
  "weight_dataset": "catalog/weight_imaging_mean1"
}

## Fiducial Theory And Windowing Check

This builds the GODMAX fiducial model once and checks the JAX-native data vector against the existing measurement wrapper. If this fails, do not run sampling.

In [30]:

if RUN_FIDUCIAL_WINDOWING_CHECK:
    fid_check = run_step("compare_fiducial_windowing", lambda: hmc31.compare_fiducial_windowing(context))
    print("allclose:", fid_check["allclose"])
    print("max_abs_delta:", fid_check["max_abs_delta"])
    print("max_rel_delta:", fid_check["max_rel_delta"])
    print("raw kSZ median C_ell by pz:", fid_check["ksz_median_raw_by_pz"])
else:
    fid_check = None
    print("RUN_FIDUCIAL_WINDOWING_CHECK=False; skipped wrapper/windowing comparison.")

RUN_FIDUCIAL_WINDOWING_CHECK=False; skipped wrapper/windowing comparison.

In [31]:

def fiducial_value_check():
    fid = hmc31.pack_fiducial_sample(context.parameter_specs)
    theory = hmc31.evaluate_sample_theory_vector(context, fid)
    chi2 = hmc31.whitened_chi2(context.likelihood, theory)
    theory_np = np.asarray(theory)
    return {
        "theory_size": int(theory_np.size),
        "theory_finite": bool(np.all(np.isfinite(theory_np))),
        "theory_nan_count": int(np.sum(~np.isfinite(theory_np))),
        "chi2": float(np.asarray(chi2)),
        "chi2_finite": bool(np.isfinite(np.asarray(chi2))),
        "theory_min": float(np.nanmin(theory_np)),
        "theory_max": float(np.nanmax(theory_np)),
    }

if RUN_FIDUCIAL_VALUE_CHECK:
    fid_value_report = run_step("fiducial finite-value check", fiducial_value_check)
    print(json.dumps(fid_value_report, indent=2))
else:
    fid_value_report = None
    print("RUN_FIDUCIAL_VALUE_CHECK=False; skipped fiducial finite-value check.")

RUN_FIDUCIAL_VALUE_CHECK=False; skipped fiducial finite-value check.

## NumPyro Initialization Diagnostic

This is the same check that NUTS performs before sampling. `validate_grad=False` only checks the model value. `validate_grad=True` also checks gradients. NUTS needs the second check to pass.

In [32]:

if RUN_INITIALIZATION_DIAGNOSTIC:
    init_report = run_step("numpyro initialize_model diagnostics", lambda: hmc31.initialization_diagnostics(context, settings))
    print(json.dumps(hmc31.gmt.to_jsonable(init_report), indent=2))
    valid_init = all(check.get("ok", False) for check in init_report["checks"])
else:
    init_report = {"checks": []}
    valid_init = True
    print("RUN_INITIALIZATION_DIAGNOSTIC=False; skipping pre-NUTS initialization diagnostic.")

print("valid_init_for_nuts:", valid_init)

RUN_INITIALIZATION_DIAGNOSTIC=False; skipping pre-NUTS initialization diagnostic.
valid_init_for_nuts: True

## Direct Physical-Parameter Gradient Diagnostic

This bypasses NumPyro's constrained-site initialization wrapper and differentiates the whitened chi-square directly with respect to the 31 physical parameters. If this reports finite gradients but NumPyro init fails, the problem is likely in NumPyro's Uniform transform. If this reports bad gradients, the issue is in the theory/likelihood path itself.

In [33]:
if RUN_PHYSICAL_GRAD_DIAGNOSTIC:
    physical_grad_report = run_step(
        "physical parameter value_and_grad diagnostics",
        lambda: hmc31.physical_gradient_diagnostics(context),
    )
    print(json.dumps(hmc31.gmt.to_jsonable(physical_grad_report), indent=2))
    if physical_grad_report.get("bad_gradients"):
        display(pd.DataFrame(physical_grad_report["bad_gradients"]))
else:
    physical_grad_report = None
    print("RUN_PHYSICAL_GRAD_DIAGNOSTIC=False; skipped direct physical gradient diagnostic.")

RUN_PHYSICAL_GRAD_DIAGNOSTIC=False; skipped direct physical gradient diagnostic.

## Optional Finite-Difference Value Scan

Run this when gradients fail. It checks whether small positive/negative moves in selected physical parameters still give finite chi-square values. Finite differences being well behaved while autodiff fails points to a differentiability or JAX tracing issue rather than an invalid model value.

In [34]:
RUN_FINITE_DIFFERENCE_SCAN = False
FINITE_DIFFERENCE_PARAMETER_INDICES = list(range(len(context.parameter_specs)))

if RUN_FINITE_DIFFERENCE_SCAN:
    fd_rows = run_step(
        "finite-difference scan",
        lambda: hmc31.finite_difference_diagnostics(
            context,
            parameter_indices=FINITE_DIFFERENCE_PARAMETER_INDICES,
            rel_step=1.0e-4,
            abs_step=1.0e-5,
        ),
    )
    fd_table = pd.DataFrame(fd_rows)
    display(fd_table)
else:
    print("Set RUN_FINITE_DIFFERENCE_SCAN=True and rerun this cell to scan finite differences.")

Set RUN_FINITE_DIFFERENCE_SCAN=True and rerun this cell to scan finite differences.

## Optional Per-Parameter JVP Gradient Scan

Run this when initialization fails. It probes the derivative of the whitened chi-square with respect to each physical parameter at the fiducial point using one forward-mode directional derivative at a time. This is expensive because each row can trace/evaluate the theory path.

In [35]:
RUN_JVP_SCAN = False
JVP_PARAMETER_INDICES = list(range(len(context.parameter_specs)))

if RUN_JVP_SCAN:
    jvp_rows = run_step(
        "per-parameter JVP scan",
        lambda: hmc31.physical_jvp_diagnostics(context, parameter_indices=JVP_PARAMETER_INDICES),
    )
    jvp_table = pd.DataFrame(jvp_rows)
    display(jvp_table)
else:
    print("Set RUN_JVP_SCAN=True and rerun this cell to scan forward-mode gradients parameter by parameter.")

Set RUN_JVP_SCAN=True and rerun this cell to scan forward-mode gradients parameter by parameter.

## Run NUTS Locally

This cell runs the same sampler machinery as the CLI but stays inside the notebook. It catches and prints the full error. If `REQUIRE_VALID_INIT_BEFORE_NUTS=True`, the cell stops before NUTS when the init diagnostic has already failed.

In [36]:
if REQUIRE_VALID_INIT_BEFORE_NUTS and not valid_init:
    raise RuntimeError(
        "Skipping NUTS because initialization gradient validation failed. "
        "Inspect init_report and optionally run the JVP scan above. "
        "Set REQUIRE_VALID_INIT_BEFORE_NUTS=False if you explicitly want to reproduce the NUTS failure."
    )

mcmc = run_step("run_hmc", lambda: hmc31.run_hmc(context, smoke=SMOKE, overrides=SAMPLER_OVERRIDES))
mcmc.print_summary()

extra = {k: np.asarray(v) for k, v in mcmc.get_extra_fields().items()}
print("extra fields:", {k: v.shape for k, v in extra.items()})
if "diverging" in extra:
    print("divergences:", int(np.sum(extra["diverging"])))
if "accept_prob" in extra:
    print("mean accept_prob:", float(np.mean(extra["accept_prob"])))
if "num_steps" in extra:
    print("num_steps min/median/max:", np.min(extra["num_steps"]), np.median(extra["num_steps"]), np.max(extra["num_steps"]))

[2026-06-04 00:15:25] START run_hmc
[2026-06-04 00:15:25] [hmc] configuring NUTS num_chains=1 chain_method=sequential num_warmup=80 num_samples=800 max_tree_depth=4 target_accept_prob=0.8 dense_mass=True progress_bar=True
[2026-06-04 00:15:25] [hmc] mcmc.run begin

sample: 100%|██████████| 880/880 [15:04<00:00,  1.03s/it, 7 steps of size 2.82e-02. acc. prob=0.25]

[2026-06-04 00:46:32] [hmc] mcmc.run done
[2026-06-04 00:46:32] DONE run_hmc in 1866.4 s

                             mean       std    median      5.0%     95.0%     n_eff     r_hat
               alpha_nt      0.06      0.00      0.06      0.06      0.06     15.33      1.01
      alphasat_Nsat_pz1      0.56      0.00      0.56      0.56      0.57     11.23      1.00
      alphasat_Nsat_pz2      0.91      0.01      0.91      0.89      0.93     26.02      1.01
      alphasat_Nsat_pz3      1.16      0.03      1.17      1.08      1.18      4.41      1.45
      alphasat_Nsat_pz4      1.49      0.04      1.51      1.43      1.51      6.17      1.22
        delta_fshmr_pz1      0.66      0.01      0.66      0.64      0.66      6.92      1.14
        delta_fshmr_pz2      0.85      0.01      0.85      0.84      0.86      6.51      1.27
        delta_fshmr_pz3      0.66      0.01      0.66      0.64      0.67      6.97      1.28
        delta_fshmr_pz4      0.64      0.01      0.65      0.62      0.65      6.82      1.13
        gamma_fshmr_pz1      0.57      0.01      0.57      0.55      0.58     13.77      1.00
        gamma_fshmr_pz2      1.95      0.01      1.96      1.93      1.97      4.56      1.47
        gamma_fshmr_pz3      1.73      0.01      1.72      1.71      1.74      6.56      1.30
        gamma_fshmr_pz4      2.06      0.01      2.06      2.04      2.07     13.74      1.01
    log10M1_a_fshmr_pz1     -0.64      0.01     -0.64     -0.66     -0.61      5.88      1.01
    log10M1_a_fshmr_pz2      0.09      0.05      0.10     -0.01      0.13      6.16      1.29
    log10M1_a_fshmr_pz3     -1.34      0.07     -1.37     -1.39     -1.23      5.87      1.25
    log10M1_a_fshmr_pz4     -2.52      0.02     -2.53     -2.53     -2.50      7.63      1.15
      log10M1_fshmr_pz1     13.86      0.02     13.86     13.83     13.88      6.14      1.02
      log10M1_fshmr_pz2     14.42      0.02     14.43     14.38     14.44      6.21      1.27
      log10M1_fshmr_pz3     13.67      0.02     13.67     13.63     13.70      3.44      1.78
      log10M1_fshmr_pz4     13.40      0.07     13.43     13.28     13.46      5.30      1.29
              log10_Mc0     13.74      0.01     13.74     13.73     13.75      3.84      1.76
  log10_Mstar0_theta_ej     15.37      0.02     15.37     15.34     15.39      7.43      1.02
                mu_beta      0.07      0.00      0.07      0.07      0.07      4.47      1.40
          nu_theta_ej_M     -0.73      0.02     -0.74     -0.75     -0.69      6.12      1.22
          nu_theta_ej_z     -0.92      0.02     -0.91     -0.95     -0.91      5.98      1.29
   siglogMstar_Ncen_pz1      0.31      0.00      0.31      0.31      0.32     15.77      1.20
   siglogMstar_Ncen_pz2      0.06      0.00      0.06      0.06      0.06      7.87      1.16
   siglogMstar_Ncen_pz3      0.37      0.01      0.37      0.34      0.38      5.48      1.29
   siglogMstar_Ncen_pz4      0.36      0.00      0.36      0.36      0.36      7.03      1.23
             theta_ej_0      2.98      0.11      3.03      2.80      3.06      5.72      1.24

Number of divergences: 397
extra fields: {'potential_energy': (800,), 'diverging': (800,), 'accept_prob': (800,), 'num_steps': (800,)}
divergences: 397
mean accept_prob: 0.25116082629658726
num_steps min/median/max: 4 15.0 15

## Save Outputs

In [37]:

if "mcmc" not in globals():
    raise RuntimeError("No `mcmc` object exists yet. Run the sampler cell first.")

if SAVE_OUTPUTS_AFTER_SAMPLING:
    saved = run_step("save_fit_outputs", lambda: hmc31.save_fit_outputs(context, mcmc, smoke=SMOKE, output_dir=OUTPUT_DIR))
    print(json.dumps({k: str(v) if k != "plots" else [str(p) for p in v] for k, v in saved.items()}, indent=2))
else:
    print("SAVE_OUTPUTS_AFTER_SAMPLING=False; outputs not written.")

[2026-06-04 00:46:32] START save_fit_outputs
[2026-06-04 00:46:32] [hmc] saving outputs begin

[2026-06-04 00:49:20] [hmc] saving outputs done best_chi2=9.10108050e+03
[2026-06-04 00:49:20] DONE save_fit_outputs in 167.8 s
{
  "chain": "/mnt/ceph/users/spandey/ltu-godmax/GODMAX/notebooks/xDESI/survey_measure/outputs/godmax_multiprobe_fast1024_true_nz_hmc_stage31_local/chain_smoke_stage31.npz",
  "bestfit_params": "/mnt/ceph/users/spandey/ltu-godmax/GODMAX/notebooks/xDESI/survey_measure/outputs/godmax_multiprobe_fast1024_true_nz_hmc_stage31_local/bestfit_params_smoke_stage31.yaml",
  "bestfit_theory_vector": "/mnt/ceph/users/spandey/ltu-godmax/GODMAX/notebooks/xDESI/survey_measure/outputs/godmax_multiprobe_fast1024_true_nz_hmc_stage31_local/bestfit_theory_data_vector_smoke_stage31.npz",
  "summary": "/mnt/ceph/users/spandey/ltu-godmax/GODMAX/notebooks/xDESI/survey_measure/outputs/godmax_multiprobe_fast1024_true_nz_hmc_stage31_local/fit_summary_smoke_stage31.json",
  "pdf": "/mnt/ceph/users/spandey/ltu-godmax/GODMAX/notebooks/xDESI/survey_measure/outputs/godmax_multiprobe_fast1024_true_nz_hmc_stage31_local/posterior_predictive_comparison_smoke_stage31.pdf",
  "plots": [
    "/mnt/ceph/users/spandey/ltu-godmax/GODMAX/notebooks/xDESI/survey_measure/outputs/godmax_multiprobe_fast1024_true_nz_hmc_stage31_local/fast1024_godmax_comparison_des_shear_EE.png",
    "/mnt/ceph/users/spandey/ltu-godmax/GODMAX/notebooks/xDESI/survey_measure/outputs/godmax_multiprobe_fast1024_true_nz_hmc_stage31_local/fast1024_godmax_comparison_act_y_des_shear_E.png",
    "/mnt/ceph/users/spandey/ltu-godmax/GODMAX/notebooks/xDESI/survey_measure/outputs/godmax_multiprobe_fast1024_true_nz_hmc_stage31_local/fast1024_godmax_comparison_desi_g_auto.png",
    "/mnt/ceph/users/spandey/ltu-godmax/GODMAX/notebooks/xDESI/survey_measure/outputs/godmax_multiprobe_fast1024_true_nz_hmc_stage31_local/fast1024_godmax_comparison_desi_g_act_y.png",
    "/mnt/ceph/users/spandey/ltu-godmax/GODMAX/notebooks/xDESI/survey_measure/outputs/godmax_multiprobe_fast1024_true_nz_hmc_stage31_local/fast1024_godmax_comparison_desi_g_des_shear_E.png",
    "/mnt/ceph/users/spandey/ltu-godmax/GODMAX/notebooks/xDESI/survey_measure/outputs/godmax_multiprobe_fast1024_true_nz_hmc_stage31_local/fast1024_godmax_comparison_desi_g_act_kappa.png",
    "/mnt/ceph/users/spandey/ltu-godmax/GODMAX/notebooks/xDESI/survey_measure/outputs/godmax_multiprobe_fast1024_true_nz_hmc_stage31_local/fast1024_godmax_comparison_desi_pi_act_T.png"
  ]
}

## Posterior Quick Look

In [38]:

if "mcmc" not in globals():
    raise RuntimeError("No `mcmc` object exists yet. Run the sampler cell first.")

samples = mcmc.get_samples(group_by_chain=False)
rows = []
for spec in context.parameter_specs:
    arr = np.asarray(samples[spec.name])
    rows.append(
        {
            "name": spec.name,
            "mean": float(np.mean(arr)),
            "std": float(np.std(arr)),
            "p16": float(np.percentile(arr, 16)),
            "p50": float(np.percentile(arr, 50)),
            "p84": float(np.percentile(arr, 84)),
            "fiducial": spec.fiducial,
            "prior_min": spec.prior_min,
            "prior_max": spec.prior_max,
        }
    )
posterior_table = pd.DataFrame(rows)
posterior_table

,name,mean,std,p16,p50,p84,fiducial,prior_min,prior_max
0,log10_Mstar0_theta_ej,15.368857,0.018571,15.365991,15.372991,15.382737,15.0000,14.000,16.5
1,theta_ej_0,2.984818,0.106476,2.933461,3.031674,3.042026,2.0000,0.500,8.0
2,nu_theta_ej_M,-0.733409,0.024415,-0.745457,-0.743686,-0.718491,-0.3300,-1.000,1.0
3,nu_theta_ej_z,-0.919408,0.018794,-0.932442,-0.912972,-0.908188,-1.2200,-2.000,2.0
4,log10_Mc0,13.737588,0.005678,13.731902,13.737067,13.741899,13.7500,13.000,16.0
5,mu_beta,0.072525,0.000788,0.071858,0.072279,0.073473,0.0762,0.005,1.5
6,alpha_nt,0.058659,0.000560,0.058354,0.058719,0.058991,0.0500,0.000,0.5
7,log10M1_fshmr_pz1,13.860460,0.015866,13.853628,13.861811,13.874080,14.5913,11.000,15.5
8,log10M1_fshmr_pz2,14.418669,0.020560,14.408745,14.425544,14.431929,14.6232,11.000,15.5
9,log10M1_fshmr_pz3,13.671433,0.022151,13.649492,13.665282,13.696971,14.5384,11.000,15.5
10,log10M1_fshmr_pz4,13.404897,0.071284,13.351984,13.433958,13.449742,13.7882,11.000,15.5
11,log10M1_a_fshmr_pz1,-0.637905,0.014009,-0.651056,-0.638925,-0.623573,-1.2424,-3.000,3.0
12,log10M1_a_fshmr_pz2,0.088567,0.049585,0.064689,0.104481,0.120750,-0.6887,-3.000,3.0
13,log10M1_a_fshmr_pz3,-1.344170,0.067334,-1.380921,-1.369082,-1.312506,-1.3134,-3.000,3.0
14,log10M1_a_fshmr_pz4,-2.519951,0.017695,-2.528299,-2.526153,-2.515071,-2.4661,-3.000,3.0
15,delta_fshmr_pz1,0.655827,0.012775,0.648922,0.660170,0.662836,0.5337,0.001,1.5
16,delta_fshmr_pz2,0.850966,0.008295,0.844519,0.848296,0.858172,0.8247,0.001,1.5
17,delta_fshmr_pz3,0.658379,0.012163,0.655895,0.661499,0.666519,0.5177,0.001,1.5
18,delta_fshmr_pz4,0.642025,0.012374,0.637330,0.646624,0.649041,0.4893,0.001,1.5
19,gamma_fshmr_pz1,0.571912,0.007819,0.569599,0.571327,0.574273,0.6581,0.010,3.0
20,gamma_fshmr_pz2,1.952980,0.014329,1.935333,1.957757,1.963745,1.8305,0.010,3.0
21,gamma_fshmr_pz3,1.725434,0.010258,1.717158,1.722894,1.735798,1.7547,0.010,3.0
22,gamma_fshmr_pz4,2.056442,0.012872,2.049900,2.057220,2.065261,1.8496,0.010,3.0
23,siglogMstar_Ncen_pz1,0.314381,0.002486,0.313066,0.314887,0.316202,0.2277,0.050,1.0
24,siglogMstar_Ncen_pz2,0.057057,0.002778,0.055891,0.056031,0.057268,0.2180,0.050,1.0
25,siglogMstar_Ncen_pz3,0.365861,0.014593,0.357413,0.371625,0.373758,0.2525,0.050,1.0
26,siglogMstar_Ncen_pz4,0.360982,0.001750,0.359624,0.360523,0.362805,0.2338,0.050,1.0
27,alphasat_Nsat_pz1,0.561748,0.003270,0.558497,0.561609,0.564578,0.9053,0.400,2.2
28,alphasat_Nsat_pz2,0.910887,0.013609,0.899221,0.910268,0.924286,1.6872,0.400,2.2
29,alphasat_Nsat_pz3,1.155668,0.032566,1.114303,1.166713,1.178758,1.0483,0.400,2.2
30,alphasat_Nsat_pz4,1.492040,0.041383,1.476588,1.509177,1.511951,1.1953,0.400,2.2

## Command-Line Equivalents

These are useful only after the notebook diagnostics show that initialization is valid.

In [39]:

PYTHON = "/mnt/home/spandey/miniconda3/envs/ili-sbi/bin/python"
RUNNER = REPO_ROOT / "notebooks" / "xDESI" / "survey_measure" / "run_godmax_multiprobe_hmc_stage31.py"
print(f"{PYTHON} {RUNNER} --platform gpu --smoke --debug-init")
print(f"{PYTHON} {RUNNER} --platform gpu --debug-init")

/mnt/home/spandey/miniconda3/envs/ili-sbi/bin/python /mnt/ceph/users/spandey/ltu-godmax/GODMAX/notebooks/xDESI/survey_measure/run_godmax_multiprobe_hmc_stage31.py --platform gpu --smoke --debug-init
/mnt/home/spandey/miniconda3/envs/ili-sbi/bin/python /mnt/ceph/users/spandey/ltu-godmax/GODMAX/notebooks/xDESI/survey_measure/run_godmax_multiprobe_hmc_stage31.py --platform gpu --debug-init